/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.5 */

#ifndef PB_PARTICLE_CLOUD_CLOUD_CLOUD_NEW_PB_H_INCLUDED
#define PB_PARTICLE_CLOUD_CLOUD_CLOUD_NEW_PB_H_INCLUDED
#include <pb.h>
#include "describe.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _particle_cloud_HelloRequest_Flag { 
    particle_cloud_HelloRequest_Flag_FLAG_NONE = 0, 
    particle_cloud_HelloRequest_Flag_FLAG_SAFE_MODE = 1, 
    particle_cloud_HelloRequest_Flag_FLAG_UPDATE_DISABLED = 2 
} particle_cloud_HelloRequest_Flag;

typedef enum _particle_cloud_HelloResponse_Flag { 
    particle_cloud_HelloResponse_Flag_FLAG_NONE = 0, 
    particle_cloud_HelloResponse_Flag_FLAG_UPDATE_PENDING = 1, 
    particle_cloud_HelloResponse_Flag_FLAG_UPDATE_CHECK_PENDING = 2 
} particle_cloud_HelloResponse_Flag;

typedef enum _particle_cloud_DescriptionRequest_SystemFlag { 
    particle_cloud_DescriptionRequest_SystemFlag_SYSTEM_FLAG_NONE = 0, 
    particle_cloud_DescriptionRequest_SystemFlag_SYSTEM_FLAG_MODULE_ALL = 1, 
    particle_cloud_DescriptionRequest_SystemFlag_SYSTEM_FLAG_MODULE_DEPENDENCIES = 2, 
    particle_cloud_DescriptionRequest_SystemFlag_SYSTEM_FLAG_MODULE_SYSTEM_HASH = 4, 
    particle_cloud_DescriptionRequest_SystemFlag_SYSTEM_FLAG_MODULE_APP_HASH = 8, 
    particle_cloud_DescriptionRequest_SystemFlag_SYSTEM_FLAG_MODULE_CERTIFICATE_INFO = 16, 
    particle_cloud_DescriptionRequest_SystemFlag_SYSTEM_FLAG_ASSET_ALL = 32, 
    particle_cloud_DescriptionRequest_SystemFlag_SYSTEM_FLAG_ASSET_HASH = 64, 
    particle_cloud_DescriptionRequest_SystemFlag_SYSTEM_FLAG_CELLULAR_ALL = 128, 
    particle_cloud_DescriptionRequest_SystemFlag_SYSTEM_FLAG_CELLULAR_IMEI_ICCID = 256, 
    particle_cloud_DescriptionRequest_SystemFlag_SYSTEM_FLAG_CELLULAR_MODEM_FIRMWARE_VERSION = 512, 
    particle_cloud_DescriptionRequest_SystemFlag_SYSTEM_FLAG_ALL = 2147483647 
} particle_cloud_DescriptionRequest_SystemFlag;

typedef enum _particle_cloud_DescriptionRequest_AppFlag { 
    particle_cloud_DescriptionRequest_AppFlag_APP_FLAG_NONE = 0, 
    particle_cloud_DescriptionRequest_AppFlag_APP_FLAG_LEGACY_FUNCTIONS = 1, 
    particle_cloud_DescriptionRequest_AppFlag_APP_FLAG_LEGACY_VARIABLES = 2, 
    particle_cloud_DescriptionRequest_AppFlag_APP_FLAG_SUBSCRIPTIONS = 4, 
    particle_cloud_DescriptionRequest_AppFlag_APP_FLAG_CONSTRAINED_SUBSCRIPTIONS = 8, 
    particle_cloud_DescriptionRequest_AppFlag_APP_FLAG_ALL = 2147483647 
} particle_cloud_DescriptionRequest_AppFlag;

typedef enum _particle_cloud_DescriptionResponse_AppDescription_LegacyVariable_Type { 
    particle_cloud_DescriptionResponse_AppDescription_LegacyVariable_Type_TYPE_INVALID = 0, 
    particle_cloud_DescriptionResponse_AppDescription_LegacyVariable_Type_TYPE_BOOL = 1, 
    particle_cloud_DescriptionResponse_AppDescription_LegacyVariable_Type_TYPE_INT32 = 2, 
    particle_cloud_DescriptionResponse_AppDescription_LegacyVariable_Type_TYPE_DOUBLE = 3, 
    particle_cloud_DescriptionResponse_AppDescription_LegacyVariable_Type_TYPE_STRING = 4 
} particle_cloud_DescriptionResponse_AppDescription_LegacyVariable_Type;

typedef enum _particle_cloud_DiagnosticsRequest_Category { 
    particle_cloud_DiagnosticsRequest_Category_CATEGORY_NONE = 0, 
    particle_cloud_DiagnosticsRequest_Category_CATEGORY_ALL = 1, 
    particle_cloud_DiagnosticsRequest_Category_CATEGORY_NETWORK_ALL = 2, 
    particle_cloud_DiagnosticsRequest_Category_CATEGORY_NETWORK_STATUS = 4, 
    particle_cloud_DiagnosticsRequest_Category_CATEGORY_NETWORK_PRIMARY_SIGNAL = 8, 
    particle_cloud_DiagnosticsRequest_Category_CATEGORY_NETWORK_ALTERNATE_SIGNAL = 16, 
    particle_cloud_DiagnosticsRequest_Category_CATEGORY_NETWORK_CELLULAR_IDENTITY = 32 
} particle_cloud_DiagnosticsRequest_Category;

/* Struct definitions */
typedef struct _particle_cloud_DescriptionResponse_AppDescription { 
    /* *
 Categories of diagnostic sources to query.

 The value is a combination of flags defined by the `Category` enum. */
    pb_callback_t subscriptions; 
    /* *
 IDs of diagnostic sources to query. */
    pb_callback_t legacy_functions; 
    pb_callback_t legacy_variables; 
} particle_cloud_DescriptionResponse_AppDescription;

typedef struct _particle_cloud_DescriptionResponse_AppDescription_LegacyFunction { 
    /* *
 Event name. */
    pb_callback_t name; 
} particle_cloud_DescriptionResponse_AppDescription_LegacyFunction;

/* *
 Probe how long the carrier's NAT keeps the device's UDP source mapping
 alive. The service waits `delay_ms` before replying; if the response
 arrives, the binding survived ≥ `delay_ms`. */
typedef struct _particle_cloud_DiagnosticsResponse { 
    /* *
 Requested delay before the service replies (milliseconds). */
    pb_callback_t sources; 
} particle_cloud_DiagnosticsResponse;

typedef struct _particle_cloud_EventResponse { 
    char dummy_field;
} particle_cloud_EventResponse;

typedef struct _particle_cloud_DescriptionRequest { 
    bool has_system_flags;
    uint32_t system_flags; 
    bool has_app_flags;
    uint32_t app_flags; 
} particle_cloud_DescriptionRequest;

typedef PB_BYTES_ARRAY_T(20) particle_cloud_DescriptionResponse_system_description_hash_t;
typedef PB_BYTES_ARRAY_T(20) particle_cloud_DescriptionResponse_app_description_hash_t;
typedef struct _particle_cloud_DescriptionResponse { 
    bool has_system_description;
    particle_cloud_SystemDescribe system_description; 
    bool has_app_description;
    particle_cloud_DescriptionResponse_AppDescription app_description; 
    bool has_system_description_hash;
    particle_cloud_DescriptionResponse_system_description_hash_t system_description_hash; 
    bool has_app_description_hash;
    particle_cloud_DescriptionResponse_app_description_hash_t app_description_hash; 
} particle_cloud_DescriptionResponse;

typedef struct _particle_cloud_DescriptionResponse_AppDescription_LegacyVariable { 
    pb_callback_t name; 
    particle_cloud_DescriptionResponse_AppDescription_LegacyVariable_Type type; 
} particle_cloud_DescriptionResponse_AppDescription_LegacyVariable;

typedef struct _particle_cloud_DescriptionResponse_AppDescription_Subscription { 
    /* *
 Diagnostic sources. */
    pb_callback_t prefix; 
    bool constrained; 
} particle_cloud_DescriptionResponse_AppDescription_Subscription;

/* *
 UDP transport envelope. Uplink-only — service-to-device packets are bare
 constrained-protocol frames with no envelope. */
typedef struct _particle_cloud_DiagnosticsRequest { 
    /* *
 Envelope version. Must be 1 for this design. */
    bool has_categories;
    uint32_t categories; 
    /* *
 NTN UDP ID — per-device identifier provisioned in the device DB. Acts as
 a lightweight gate (unknown IDs are dropped). */
    pb_callback_t ids; 
} particle_cloud_DiagnosticsRequest;

typedef struct _particle_cloud_DiagnosticsResponse_Source { 
    /* *
 Echoed from the request. */
    uint32_t id; 
    /* *
 Delay the service actually held the reply for. Differs from the
 request's `delay_ms` when the service clamped it. Firmware MUST use
 this value, not its own requested delay, when concluding "NAT binding
 survived ≥ X". */
    pb_callback_t data; 
} particle_cloud_DiagnosticsResponse_Source;

typedef struct _particle_cloud_EventRequest { 
    pb_size_t which_type;
    union {
        pb_callback_t name;
        uint32_t code;
    } type; 
    pb_callback_t data; 
} particle_cloud_EventRequest;

typedef PB_BYTES_ARRAY_T(20) particle_cloud_HelloRequest_system_description_hash_t;
typedef PB_BYTES_ARRAY_T(20) particle_cloud_HelloRequest_app_description_hash_t;
/* *
 A request sent by the device when it starts or resumes a session with the server. */
typedef struct _particle_cloud_HelloRequest { 
    /* *
 Module version of the system firmware. */
    uint32_t system_version; 
    /* *
 Product firmware version.

 If not set, the device is not running a product firmware. */
    bool has_product_version;
    uint32_t product_version; 
    /* *
 Combination of flags defined by the `Flag` enum. */
    uint32_t flags; 
    /* *
 SHA-1 hash of the system description. */
    particle_cloud_HelloRequest_system_description_hash_t system_description_hash; 
    /* *
 SHA-1 hash of the application description.

 If not set, the device is not running an application firmware. */
    bool has_app_description_hash;
    particle_cloud_HelloRequest_app_description_hash_t app_description_hash; 
} particle_cloud_HelloRequest;

/* *
 A response for `HelloRequest`. */
typedef struct _particle_cloud_HelloResponse { 
    /* *
 Combination of flags defined by the `Flag` enum. */
    uint32_t flags; 
} particle_cloud_HelloResponse;

typedef struct _particle_cloud_NatProbeRequest { 
    uint32_t delay_ms; 
    pb_callback_t nonce; 
} particle_cloud_NatProbeRequest;

typedef struct _particle_cloud_NatProbeResponse { 
    pb_callback_t nonce; 
    uint32_t actual_delay_ms; 
} particle_cloud_NatProbeResponse;

typedef struct _particle_cloud_UdpEnvelope { 
    uint32_t ver; 
    pb_callback_t id; 
    pb_callback_t data; 
} particle_cloud_UdpEnvelope;


/* Helper constants for enums */
#define _particle_cloud_HelloRequest_Flag_MIN particle_cloud_HelloRequest_Flag_FLAG_NONE
#define _particle_cloud_HelloRequest_Flag_MAX particle_cloud_HelloRequest_Flag_FLAG_UPDATE_DISABLED
#define _particle_cloud_HelloRequest_Flag_ARRAYSIZE ((particle_cloud_HelloRequest_Flag)(particle_cloud_HelloRequest_Flag_FLAG_UPDATE_DISABLED+1))

#define _particle_cloud_HelloResponse_Flag_MIN particle_cloud_HelloResponse_Flag_FLAG_NONE
#define _particle_cloud_HelloResponse_Flag_MAX particle_cloud_HelloResponse_Flag_FLAG_UPDATE_CHECK_PENDING
#define _particle_cloud_HelloResponse_Flag_ARRAYSIZE ((particle_cloud_HelloResponse_Flag)(particle_cloud_HelloResponse_Flag_FLAG_UPDATE_CHECK_PENDING+1))

#define _particle_cloud_DescriptionRequest_SystemFlag_MIN particle_cloud_DescriptionRequest_SystemFlag_SYSTEM_FLAG_NONE
#define _particle_cloud_DescriptionRequest_SystemFlag_MAX particle_cloud_DescriptionRequest_SystemFlag_SYSTEM_FLAG_ALL
#define _particle_cloud_DescriptionRequest_SystemFlag_ARRAYSIZE ((particle_cloud_DescriptionRequest_SystemFlag)(particle_cloud_DescriptionRequest_SystemFlag_SYSTEM_FLAG_ALL+1))

#define _particle_cloud_DescriptionRequest_AppFlag_MIN particle_cloud_DescriptionRequest_AppFlag_APP_FLAG_NONE
#define _particle_cloud_DescriptionRequest_AppFlag_MAX particle_cloud_DescriptionRequest_AppFlag_APP_FLAG_ALL
#define _particle_cloud_DescriptionRequest_AppFlag_ARRAYSIZE ((particle_cloud_DescriptionRequest_AppFlag)(particle_cloud_DescriptionRequest_AppFlag_APP_FLAG_ALL+1))

#define _particle_cloud_DescriptionResponse_AppDescription_LegacyVariable_Type_MIN particle_cloud_DescriptionResponse_AppDescription_LegacyVariable_Type_TYPE_INVALID
#define _particle_cloud_DescriptionResponse_AppDescription_LegacyVariable_Type_MAX particle_cloud_DescriptionResponse_AppDescription_LegacyVariable_Type_TYPE_STRING
#define _particle_cloud_DescriptionResponse_AppDescription_LegacyVariable_Type_ARRAYSIZE ((particle_cloud_DescriptionResponse_AppDescription_LegacyVariable_Type)(particle_cloud_DescriptionResponse_AppDescription_LegacyVariable_Type_TYPE_STRING+1))

#define _particle_cloud_DiagnosticsRequest_Category_MIN particle_cloud_DiagnosticsRequest_Category_CATEGORY_NONE
#define _particle_cloud_DiagnosticsRequest_Category_MAX particle_cloud_DiagnosticsRequest_Category_CATEGORY_NETWORK_CELLULAR_IDENTITY
#define _particle_cloud_DiagnosticsRequest_Category_ARRAYSIZE ((particle_cloud_DiagnosticsRequest_Category)(particle_cloud_DiagnosticsRequest_Category_CATEGORY_NETWORK_CELLULAR_IDENTITY+1))


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define particle_cloud_HelloRequest_init_default {0, false, 0, 0, {0, {0}}, false, {0, {0}}}
#define particle_cloud_HelloResponse_init_default {0}
#define particle_cloud_DescriptionRequest_init_default {false, 0, false, 0}
#define particle_cloud_DescriptionResponse_init_default {false, particle_cloud_SystemDescribe_init_default, false, particle_cloud_DescriptionResponse_AppDescription_init_default, false, {0, {0}}, false, {0, {0}}}
#define particle_cloud_DescriptionResponse_AppDescription_init_default {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define particle_cloud_DescriptionResponse_AppDescription_Subscription_init_default {{{NULL}, NULL}, 0}
#define particle_cloud_DescriptionResponse_AppDescription_LegacyFunction_init_default {{{NULL}, NULL}}
#define particle_cloud_DescriptionResponse_AppDescription_LegacyVariable_init_default {{{NULL}, NULL}, _particle_cloud_DescriptionResponse_AppDescription_LegacyVariable_Type_MIN}
#define particle_cloud_DiagnosticsRequest_init_default {false, 0, {{NULL}, NULL}}
#define particle_cloud_DiagnosticsResponse_init_default {{{NULL}, NULL}}
#define particle_cloud_DiagnosticsResponse_Source_init_default {0, {{NULL}, NULL}}
#define particle_cloud_EventRequest_init_default {0, {{{NULL}, NULL}}, {{NULL}, NULL}}
#define particle_cloud_EventResponse_init_default {0}
#define particle_cloud_UdpEnvelope_init_default  {0, {{NULL}, NULL}, {{NULL}, NULL}}
#define particle_cloud_NatProbeRequest_init_default {0, {{NULL}, NULL}}
#define particle_cloud_NatProbeResponse_init_default {{{NULL}, NULL}, 0}
#define particle_cloud_HelloRequest_init_zero    {0, false, 0, 0, {0, {0}}, false, {0, {0}}}
#define particle_cloud_HelloResponse_init_zero   {0}
#define particle_cloud_DescriptionRequest_init_zero {false, 0, false, 0}
#define particle_cloud_DescriptionResponse_init_zero {false, particle_cloud_SystemDescribe_init_zero, false, particle_cloud_DescriptionResponse_AppDescription_init_zero, false, {0, {0}}, false, {0, {0}}}
#define particle_cloud_DescriptionResponse_AppDescription_init_zero {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define particle_cloud_DescriptionResponse_AppDescription_Subscription_init_zero {{{NULL}, NULL}, 0}
#define particle_cloud_DescriptionResponse_AppDescription_LegacyFunction_init_zero {{{NULL}, NULL}}
#define particle_cloud_DescriptionResponse_AppDescription_LegacyVariable_init_zero {{{NULL}, NULL}, _particle_cloud_DescriptionResponse_AppDescription_LegacyVariable_Type_MIN}
#define particle_cloud_DiagnosticsRequest_init_zero {false, 0, {{NULL}, NULL}}
#define particle_cloud_DiagnosticsResponse_init_zero {{{NULL}, NULL}}
#define particle_cloud_DiagnosticsResponse_Source_init_zero {0, {{NULL}, NULL}}
#define particle_cloud_EventRequest_init_zero    {0, {{{NULL}, NULL}}, {{NULL}, NULL}}
#define particle_cloud_EventResponse_init_zero   {0}
#define particle_cloud_UdpEnvelope_init_zero     {0, {{NULL}, NULL}, {{NULL}, NULL}}
#define particle_cloud_NatProbeRequest_init_zero {0, {{NULL}, NULL}}
#define particle_cloud_NatProbeResponse_init_zero {{{NULL}, NULL}, 0}

/* Field tags (for use in manual encoding/decoding) */
#define particle_cloud_DescriptionResponse_AppDescription_subscriptions_tag 1
#define particle_cloud_DescriptionResponse_AppDescription_legacy_functions_tag 2
#define particle_cloud_DescriptionResponse_AppDescription_legacy_variables_tag 3
#define particle_cloud_DescriptionResponse_AppDescription_LegacyFunction_name_tag 1
#define particle_cloud_DiagnosticsResponse_sources_tag 1
#define particle_cloud_DescriptionRequest_system_flags_tag 1
#define particle_cloud_DescriptionRequest_app_flags_tag 2
#define particle_cloud_DescriptionResponse_system_description_tag 1
#define particle_cloud_DescriptionResponse_app_description_tag 2
#define particle_cloud_DescriptionResponse_system_description_hash_tag 3
#define particle_cloud_DescriptionResponse_app_description_hash_tag 4
#define particle_cloud_DescriptionResponse_AppDescription_LegacyVariable_name_tag 1
#define particle_cloud_DescriptionResponse_AppDescription_LegacyVariable_type_tag 2
#define particle_cloud_DescriptionResponse_AppDescription_Subscription_prefix_tag 1
#define particle_cloud_DescriptionResponse_AppDescription_Subscription_constrained_tag 2
#define particle_cloud_DiagnosticsRequest_categories_tag 1
#define particle_cloud_DiagnosticsRequest_ids_tag 2
#define particle_cloud_DiagnosticsResponse_Source_id_tag 1
#define particle_cloud_DiagnosticsResponse_Source_data_tag 2
#define particle_cloud_EventRequest_name_tag     1
#define particle_cloud_EventRequest_code_tag     2
#define particle_cloud_EventRequest_data_tag     3
#define particle_cloud_HelloRequest_system_version_tag 1
#define particle_cloud_HelloRequest_product_version_tag 2
#define particle_cloud_HelloRequest_flags_tag    3
#define particle_cloud_HelloRequest_system_description_hash_tag 4
#define particle_cloud_HelloRequest_app_description_hash_tag 5
#define particle_cloud_HelloResponse_flags_tag   1
#define particle_cloud_NatProbeRequest_delay_ms_tag 1
#define particle_cloud_NatProbeRequest_nonce_tag 2
#define particle_cloud_NatProbeResponse_nonce_tag 1
#define particle_cloud_NatProbeResponse_actual_delay_ms_tag 2
#define particle_cloud_UdpEnvelope_ver_tag       1
#define particle_cloud_UdpEnvelope_id_tag        2
#define particle_cloud_UdpEnvelope_data_tag      3

/* Struct field encoding specification for nanopb */
#define particle_cloud_HelloRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   system_version,    1) \
X(a, STATIC,   OPTIONAL, UINT32,   product_version,   2) \
X(a, STATIC,   SINGULAR, FIXED32,  flags,             3) \
X(a, STATIC,   SINGULAR, BYTES,    system_description_hash,   4) \
X(a, STATIC,   OPTIONAL, BYTES,    app_description_hash,   5)
#define particle_cloud_HelloRequest_CALLBACK NULL
#define particle_cloud_HelloRequest_DEFAULT NULL

#define particle_cloud_HelloResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FIXED32,  flags,             1)
#define particle_cloud_HelloResponse_CALLBACK NULL
#define particle_cloud_HelloResponse_DEFAULT NULL

#define particle_cloud_DescriptionRequest_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, FIXED32,  system_flags,      1) \
X(a, STATIC,   OPTIONAL, FIXED32,  app_flags,         2)
#define particle_cloud_DescriptionRequest_CALLBACK NULL
#define particle_cloud_DescriptionRequest_DEFAULT NULL

#define particle_cloud_DescriptionResponse_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  system_description,   1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  app_description,   2) \
X(a, STATIC,   OPTIONAL, BYTES,    system_description_hash,   3) \
X(a, STATIC,   OPTIONAL, BYTES,    app_description_hash,   4)
#define particle_cloud_DescriptionResponse_CALLBACK NULL
#define particle_cloud_DescriptionResponse_DEFAULT NULL
#define particle_cloud_DescriptionResponse_system_description_MSGTYPE particle_cloud_SystemDescribe
#define particle_cloud_DescriptionResponse_app_description_MSGTYPE particle_cloud_DescriptionResponse_AppDescription

#define particle_cloud_DescriptionResponse_AppDescription_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  subscriptions,     1) \
X(a, CALLBACK, REPEATED, MESSAGE,  legacy_functions,   2) \
X(a, CALLBACK, REPEATED, MESSAGE,  legacy_variables,   3)
#define particle_cloud_DescriptionResponse_AppDescription_CALLBACK pb_default_field_callback
#define particle_cloud_DescriptionResponse_AppDescription_DEFAULT NULL
#define particle_cloud_DescriptionResponse_AppDescription_subscriptions_MSGTYPE particle_cloud_DescriptionResponse_AppDescription_Subscription
#define particle_cloud_DescriptionResponse_AppDescription_legacy_functions_MSGTYPE particle_cloud_DescriptionResponse_AppDescription_LegacyFunction
#define particle_cloud_DescriptionResponse_AppDescription_legacy_variables_MSGTYPE particle_cloud_DescriptionResponse_AppDescription_LegacyVariable

#define particle_cloud_DescriptionResponse_AppDescription_Subscription_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   prefix,            1) \
X(a, STATIC,   SINGULAR, BOOL,     constrained,       2)
#define particle_cloud_DescriptionResponse_AppDescription_Subscription_CALLBACK pb_default_field_callback
#define particle_cloud_DescriptionResponse_AppDescription_Subscription_DEFAULT NULL

#define particle_cloud_DescriptionResponse_AppDescription_LegacyFunction_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   name,              1)
#define particle_cloud_DescriptionResponse_AppDescription_LegacyFunction_CALLBACK pb_default_field_callback
#define particle_cloud_DescriptionResponse_AppDescription_LegacyFunction_DEFAULT NULL

#define particle_cloud_DescriptionResponse_AppDescription_LegacyVariable_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   name,              1) \
X(a, STATIC,   SINGULAR, UENUM,    type,              2)
#define particle_cloud_DescriptionResponse_AppDescription_LegacyVariable_CALLBACK pb_default_field_callback
#define particle_cloud_DescriptionResponse_AppDescription_LegacyVariable_DEFAULT NULL

#define particle_cloud_DiagnosticsRequest_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, FIXED32,  categories,        1) \
X(a, CALLBACK, REPEATED, UINT32,   ids,               2)
#define particle_cloud_DiagnosticsRequest_CALLBACK pb_default_field_callback
#define particle_cloud_DiagnosticsRequest_DEFAULT NULL

#define particle_cloud_DiagnosticsResponse_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  sources,           1)
#define particle_cloud_DiagnosticsResponse_CALLBACK pb_default_field_callback
#define particle_cloud_DiagnosticsResponse_DEFAULT NULL
#define particle_cloud_DiagnosticsResponse_sources_MSGTYPE particle_cloud_DiagnosticsResponse_Source

#define particle_cloud_DiagnosticsResponse_Source_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   id,                1) \
X(a, CALLBACK, SINGULAR, BYTES,    data,              2)
#define particle_cloud_DiagnosticsResponse_Source_CALLBACK pb_default_field_callback
#define particle_cloud_DiagnosticsResponse_Source_DEFAULT NULL

#define particle_cloud_EventRequest_FIELDLIST(X, a) \
X(a, CALLBACK, ONEOF,    STRING,   (type,name,type.name),   1) \
X(a, STATIC,   ONEOF,    UINT32,   (type,code,type.code),   2) \
X(a, CALLBACK, OPTIONAL, BYTES,    data,              3)
#define particle_cloud_EventRequest_CALLBACK pb_default_field_callback
#define particle_cloud_EventRequest_DEFAULT NULL

#define particle_cloud_EventResponse_FIELDLIST(X, a) \

#define particle_cloud_EventResponse_CALLBACK NULL
#define particle_cloud_EventResponse_DEFAULT NULL

#define particle_cloud_UdpEnvelope_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   ver,               1) \
X(a, CALLBACK, SINGULAR, BYTES,    id,                2) \
X(a, CALLBACK, SINGULAR, BYTES,    data,              3)
#define particle_cloud_UdpEnvelope_CALLBACK pb_default_field_callback
#define particle_cloud_UdpEnvelope_DEFAULT NULL

#define particle_cloud_NatProbeRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   delay_ms,          1) \
X(a, CALLBACK, SINGULAR, BYTES,    nonce,             2)
#define particle_cloud_NatProbeRequest_CALLBACK pb_default_field_callback
#define particle_cloud_NatProbeRequest_DEFAULT NULL

#define particle_cloud_NatProbeResponse_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, BYTES,    nonce,             1) \
X(a, STATIC,   SINGULAR, UINT32,   actual_delay_ms,   2)
#define particle_cloud_NatProbeResponse_CALLBACK pb_default_field_callback
#define particle_cloud_NatProbeResponse_DEFAULT NULL

extern const pb_msgdesc_t particle_cloud_HelloRequest_msg;
extern const pb_msgdesc_t particle_cloud_HelloResponse_msg;
extern const pb_msgdesc_t particle_cloud_DescriptionRequest_msg;
extern const pb_msgdesc_t particle_cloud_DescriptionResponse_msg;
extern const pb_msgdesc_t particle_cloud_DescriptionResponse_AppDescription_msg;
extern const pb_msgdesc_t particle_cloud_DescriptionResponse_AppDescription_Subscription_msg;
extern const pb_msgdesc_t particle_cloud_DescriptionResponse_AppDescription_LegacyFunction_msg;
extern const pb_msgdesc_t particle_cloud_DescriptionResponse_AppDescription_LegacyVariable_msg;
extern const pb_msgdesc_t particle_cloud_DiagnosticsRequest_msg;
extern const pb_msgdesc_t particle_cloud_DiagnosticsResponse_msg;
extern const pb_msgdesc_t particle_cloud_DiagnosticsResponse_Source_msg;
extern const pb_msgdesc_t particle_cloud_EventRequest_msg;
extern const pb_msgdesc_t particle_cloud_EventResponse_msg;
extern const pb_msgdesc_t particle_cloud_UdpEnvelope_msg;
extern const pb_msgdesc_t particle_cloud_NatProbeRequest_msg;
extern const pb_msgdesc_t particle_cloud_NatProbeResponse_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define particle_cloud_HelloRequest_fields &particle_cloud_HelloRequest_msg
#define particle_cloud_HelloResponse_fields &particle_cloud_HelloResponse_msg
#define particle_cloud_DescriptionRequest_fields &particle_cloud_DescriptionRequest_msg
#define particle_cloud_DescriptionResponse_fields &particle_cloud_DescriptionResponse_msg
#define particle_cloud_DescriptionResponse_AppDescription_fields &particle_cloud_DescriptionResponse_AppDescription_msg
#define particle_cloud_DescriptionResponse_AppDescription_Subscription_fields &particle_cloud_DescriptionResponse_AppDescription_Subscription_msg
#define particle_cloud_DescriptionResponse_AppDescription_LegacyFunction_fields &particle_cloud_DescriptionResponse_AppDescription_LegacyFunction_msg
#define particle_cloud_DescriptionResponse_AppDescription_LegacyVariable_fields &particle_cloud_DescriptionResponse_AppDescription_LegacyVariable_msg
#define particle_cloud_DiagnosticsRequest_fields &particle_cloud_DiagnosticsRequest_msg
#define particle_cloud_DiagnosticsResponse_fields &particle_cloud_DiagnosticsResponse_msg
#define particle_cloud_DiagnosticsResponse_Source_fields &particle_cloud_DiagnosticsResponse_Source_msg
#define particle_cloud_EventRequest_fields &particle_cloud_EventRequest_msg
#define particle_cloud_EventResponse_fields &particle_cloud_EventResponse_msg
#define particle_cloud_UdpEnvelope_fields &particle_cloud_UdpEnvelope_msg
#define particle_cloud_NatProbeRequest_fields &particle_cloud_NatProbeRequest_msg
#define particle_cloud_NatProbeResponse_fields &particle_cloud_NatProbeResponse_msg

/* Maximum encoded size of messages (where known) */
/* particle_cloud_DescriptionResponse_size depends on runtime parameters */
/* particle_cloud_DescriptionResponse_AppDescription_size depends on runtime parameters */
/* particle_cloud_DescriptionResponse_AppDescription_Subscription_size depends on runtime parameters */
/* particle_cloud_DescriptionResponse_AppDescription_LegacyFunction_size depends on runtime parameters */
/* particle_cloud_DescriptionResponse_AppDescription_LegacyVariable_size depends on runtime parameters */
/* particle_cloud_DiagnosticsRequest_size depends on runtime parameters */
/* particle_cloud_DiagnosticsResponse_size depends on runtime parameters */
/* particle_cloud_DiagnosticsResponse_Source_size depends on runtime parameters */
/* particle_cloud_EventRequest_size depends on runtime parameters */
/* particle_cloud_UdpEnvelope_size depends on runtime parameters */
/* particle_cloud_NatProbeRequest_size depends on runtime parameters */
/* particle_cloud_NatProbeResponse_size depends on runtime parameters */
#define particle_cloud_DescriptionRequest_size   10
#define particle_cloud_EventResponse_size        0
#define particle_cloud_HelloRequest_size         61
#define particle_cloud_HelloResponse_size        5

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
